"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 4

[[blocks]]
type = "rprompt"

[[blocks.segments]]
foreground = "#007ACC"
template = " {{ .CurrentDate | date .Format }} "
style = "plain"
type = "time"

[blocks.segments.options]
time_format = "15:04:05"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#ffffff"
template = "{{ .UserName }} "
style = "plain"
type = "session"

[blocks.segments.options]
display_default = false

[[blocks.segments]]
foreground = "#35b5ff"
template = "{{ .Path }} "
style = "plain"
type = "path"

[blocks.segments.options]
style = "folder"

[[blocks.segments]]
background = "transparent"
foreground = "#2e9599"
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#f36943{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#a8216b{{ end }}",
  "{{ if gt .Ahead 0 }}#35b5ff{{ end }}",
  "{{ if gt .Behind 0 }}#f89cfa{{ end }}",
]
template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }} "
style = "plain"
type = "git"

[blocks.segments.options]
branch_template = "{{ trunc 25 .Branch }}"
fetch_status = true

[[blocks.segments]]
background = "transparent"
background_templates = ["{{ if gt .Code 0 }}#e91e63{{ end }}"]
foreground = "#ffffff"
foreground_templates = ["{{ if gt .Code 0 }}#e91e63{{ end }}"]
template = "Î» "
style = "plain"
type = "status"

[blocks.segments.options]
always_enabled = true
